"use client";

import { useWorkoutBuilderStore } from "../model/workout-builder.store";

export function useWorkoutStepper() {
  const {
    currentStep,
    selectedEquipment,
    selectedMuscles,
    selectedIntent,
    selectedDaysPerWeek,
    selectedSplitDay,
    exercisesByMuscle,
    isLoadingExercises,
    exercisesError,
    exercisesOrder,
    shufflingExerciseId,
    setStep,
    nextStep,
    prevStep,
    toggleEquipment,
    clearEquipment,
    toggleMuscle,
    clearMuscles,
    setMuscles,
    setIntent,
    setDaysPerWeek,
   selectSplitDay,
   fetchExercises,
   setExercisesOrder,
   shuffleExercise,
   pickExercise,
   deleteExercise,
   loadFromSession,
   quickMode,
   quickTimeBudget,
   isGeneratingQuick,
   quickError,
   setQuickTimeBudget,
   generateQuickSession,
    isGeneratingPlanSession,
    planSessionError,
    generatePlanSession,
   quickSetScheme,
 } = useWorkoutBuilderStore();

 const canProceedToStep2 = selectedEquipment.length > 0;
  const canProceedToStep3 = selectedMuscles.length > 0;

  return {
    currentStep,
    selectedEquipment,
    selectedMuscles,
    selectedIntent,
    selectedDaysPerWeek,
    selectedSplitDay,
    exercisesByMuscle,
    isLoadingExercises,
    exercisesError,
    goToStep: setStep,
    nextStep,
    prevStep,
    toggleEquipment,
    clearEquipment,
    toggleMuscle,
    clearMuscles,
    setMuscles,
    setIntent,
    setDaysPerWeek,
    selectSplitDay,
    canProceedToStep2,
    canProceedToStep3,
    fetchExercises,
    exercisesOrder,
    setExercisesOrder,
   shuffleExercise,
   shufflingExerciseId,
   pickExercise,
   deleteExercise,
   loadFromSession,
   quickMode,
   quickTimeBudget,
   isGeneratingQuick,
   quickError,
   setQuickTimeBudget,
   generateQuickSession,
    isGeneratingPlanSession,
    planSessionError,
    generatePlanSession,
    quickSetScheme,
 };
}
