"use client";

import { useWorkoutBuilderStore } from "../model/workout-builder.store";

export function useWorkoutStepper() {
  const {
    currentStep,
    selectedEquipment,
    selectedMuscles,
    selectedIntent,
    selectedDaysPerWeek,
    selectedSplitDay,
    exercisesByMuscle,
    isLoadingExercises,
    exercisesError,
    exercisesOrder,
    shufflingExerciseId,
    setStep,
    nextStep,
    prevStep,
    toggleEquipment,
    clearEquipment,
    toggleMuscle,
    clearMuscles,
    setMuscles,
    setIntent,
    setDaysPerWeek,
    selectSplitDay,
    fetchExercises,
    setExercisesOrder,
    shuffleExercise,
    pickExercise,
    deleteExercise,
    loadFromSession,
    quickMode,
    quickTimeBudget,
    isGeneratingQuick,
    quickError,
    setQuickTimeBudget,
    setRecommendedPlanMinutes,
    setRestIntervalSeconds,
    setWarmupRoutineEnabled,
    setWarmupExerciseCount,
    setWarmupReps,
    setCooldownRoutineEnabled,
    setCooldownExerciseCount,
    setCooldownHoldSeconds,
    generateQuickSession,
    recommendedPlanMinutes,
    restIntervalSeconds,
    warmupRoutineEnabled,
    warmupExerciseCount,
    warmupReps,
    cooldownRoutineEnabled,
    cooldownExerciseCount,
    cooldownHoldSeconds,
    isGeneratingPlanSession,
    planSessionError,
    generatePlanSession,
    quickSetScheme,
    isUsingBodyweightOnlyMode,
    isLoadingWorkoutPreferences,
    refreshWorkoutPreferences,
  } = useWorkoutBuilderStore();

  const canProceedToStep2 = selectedEquipment.length > 0 || isUsingBodyweightOnlyMode;
  const canProceedToStep3 = selectedMuscles.length > 0;

  return {
    currentStep,
    selectedEquipment,
    selectedMuscles,
    selectedIntent,
    selectedDaysPerWeek,
    selectedSplitDay,
    exercisesByMuscle,
    isLoadingExercises,
    exercisesError,
    goToStep: setStep,
    nextStep,
    prevStep,
    toggleEquipment,
    clearEquipment,
    toggleMuscle,
    clearMuscles,
    setMuscles,
    setIntent,
    setDaysPerWeek,
    selectSplitDay,
    canProceedToStep2,
    canProceedToStep3,
    fetchExercises,
    exercisesOrder,
    setExercisesOrder,
    shuffleExercise,
    shufflingExerciseId,
    pickExercise,
    deleteExercise,
    loadFromSession,
    quickMode,
    isUsingBodyweightOnlyMode,
    isLoadingWorkoutPreferences,
    quickTimeBudget,
    isGeneratingQuick,
    quickError,
    setQuickTimeBudget,
    setRecommendedPlanMinutes,
    setRestIntervalSeconds,
    setWarmupRoutineEnabled,
    setWarmupExerciseCount,
    setWarmupReps,
    setCooldownRoutineEnabled,
    setCooldownExerciseCount,
    setCooldownHoldSeconds,
    generateQuickSession,
    recommendedPlanMinutes,
    restIntervalSeconds,
    warmupRoutineEnabled,
    warmupExerciseCount,
    warmupReps,
    cooldownRoutineEnabled,
    cooldownExerciseCount,
    cooldownHoldSeconds,
    isGeneratingPlanSession,
    planSessionError,
    generatePlanSession,
    refreshWorkoutPreferences,
    quickSetScheme,
  };
}
